"""Icosahedral rotation group and the two axes an I53 cage is built on.

Everything downstream rests on this being exactly right, and an error here is
quiet: a slightly wrong axis still produces a plausible-looking assembly that
simply does not close. The group is therefore generated by closure rather than
written out, and checked against its own structure.

The rotation group I has 60 elements:

    1  identity
    24 fivefold    6 axes through opposite vertices, 72 and 144 degrees each way
    20 threefold   10 axes through opposite faces, 120 degrees each way
    15 twofold     15 axes through opposite edge midpoints

A C5 component sits on a fivefold axis and a C3 component on an adjacent
threefold axis. The angle between them is fixed by the geometry at 37.3774
degrees and is not a parameter of the design.
"""
from __future__ import annotations

import functools

import numpy as np

PHI = (1.0 + np.sqrt(5.0)) / 2.0

# Angle between a fivefold axis and its nearest threefold axis. Stated here as the
# closed form rather than a literal, so it cannot drift from the geometry.
FIVE_THREE_ANGLE_DEG = float(np.degrees(np.arccos((PHI + 1) / (np.sqrt(3) * np.sqrt(PHI + 2)))))


def rotation_matrix(axis: np.ndarray, angle_rad: float) -> np.ndarray:
    """Rotation about `axis` by `angle_rad`, via Rodrigues."""
    a = np.asarray(axis, dtype=float)
    a = a / np.linalg.norm(a)
    k = np.array([[0.0, -a[2], a[1]], [a[2], 0.0, -a[0]], [-a[1], a[0], 0.0]])
    return np.eye(3) + np.sin(angle_rad) * k + (1 - np.cos(angle_rad)) * (k @ k)


def icosahedron_vertices() -> np.ndarray:
    """The 12 vertices, as unit vectors. Fivefold axes pass through them."""
    raw = []
    for s1 in (1, -1):
        for s2 in (1, -1):
            raw += [(0.0, s1 * 1.0, s2 * PHI),
                    (s1 * 1.0, s2 * PHI, 0.0),
                    (s1 * PHI, 0.0, s2 * 1.0)]
    v = np.array(raw)
    return v / np.linalg.norm(v, axis=1, keepdims=True)


def _unique_rotations(mats: list[np.ndarray], tol: float = 1e-8) -> list[np.ndarray]:
    out: list[np.ndarray] = []
    for m in mats:
        if not any(np.allclose(m, k, atol=tol) for k in out):
            out.append(m)
    return out


@functools.lru_cache(maxsize=1)
def _rotations_cached() -> tuple:
    return tuple(map(tuple, (m.ravel() for m in _build_rotations())))


def icosahedral_rotations() -> np.ndarray:
    """All 60 proper rotations as a (60, 3, 3) array; the group is a constant."""
    return np.array([np.array(r).reshape(3, 3) for r in _rotations_cached()])


def _build_rotations() -> np.ndarray:
    """Generated by closing the set of fivefold rotations under multiplication. The
    fivefold rotations alone generate the whole group, so closure yields it exactly
    and the element count is a check rather than an assumption.
    """
    seed = [np.eye(3)]
    for axis in icosahedron_vertices():
        for k in range(1, 5):
            seed.append(rotation_matrix(axis, 2 * np.pi * k / 5))

    group = _unique_rotations(seed)
    while True:
        grown = _unique_rotations(group + [a @ b for a in group for b in group])
        if len(grown) == len(group):
            break
        group = grown
        if len(group) > 60:                                  # closure has gone wrong
            raise RuntimeError(f"icosahedral closure produced {len(group)} elements")
    return np.array(group)


def rotation_angle_deg(m: np.ndarray) -> float:
    """Rotation angle of a proper rotation matrix, in degrees."""
    return float(np.degrees(np.arccos(np.clip((np.trace(m) - 1.0) / 2.0, -1.0, 1.0))))


@functools.lru_cache(maxsize=1)
def axis_pair() -> tuple[np.ndarray, np.ndarray]:
    """A fivefold axis and the threefold axis nearest to it, both as unit vectors.

    Which pair is chosen does not matter, since the group maps any such pair onto
    any other; what matters is that they are adjacent, because a C5 and a C3
    component have to meet.
    """
    five = icosahedron_vertices()[0]

    threefold = []
    for m in icosahedral_rotations():
        if abs(rotation_angle_deg(m) - 120.0) > 1e-6:
            continue
        values, vectors = np.linalg.eig(m)
        axis = np.real(vectors[:, int(np.argmin(np.abs(values - 1.0)))])
        threefold.append(axis / np.linalg.norm(axis))

    best, best_angle = None, 180.0
    for axis in threefold:
        signed = axis if np.dot(axis, five) >= 0 else -axis
        angle = np.degrees(np.arccos(np.clip(np.dot(signed, five), -1.0, 1.0)))
        if angle < best_angle:
            best, best_angle = signed, angle
    return five, best
